### PR TITLE
Fixes for Lua transpiler!

### PR DESCRIPTION
**Pull request by Rabios**
Fixes:
1. Let transpiler generate require for bit or bit32 module if one of them found, With edit on transpiling them...
2. Fix ternary operators, It shouldn't be as functions (hilbert example didn't worked with that case...)

### CODE REVIEW

**Comment by LingDong-** [comment]
Hi @Rabios 

Thanks so much for the fixes!

- the require bit/bit32 fix -- looks good, thanks
- ternary operator - using `and`/`or` is incorrect -- if the true case evaluates to a falsy (`false`/`nil`) value the false case will be always be returned. e.g. `1 ? NULL : thing` expects `NULL` while `(1~=0) and nil or thing` in lua gives `thing`. 
- One possible way is to do a typecheck and select the `and`/`or` expression instead of lambda iff the operands are numerical types, since lua considers 0 to be true.
- The hilbert example seems to work just fine for me. Tested locally on lua/luajit and online via https://www.tutorialspoint.com/execute_lua_online.php (Lua v5.3.4). What problem are you experiencing?

**Comment by Rabios** [comment]
Problem with require when module not found, I tested it on https://repl.it so for this reason i decided to implement solve for bit operations...

About ternary operations, Lua expects to use expression after `and` if condition is true, Else uses second one after `or`.

Correct me if wrong about ternary operations...

**Comment by Rabios** [comment]
OK...I think we need to check for nullables...

**Comment by LingDong-** [comment]
Hi @Rabios, thanks for the clarification

- Seems like the reason repl.it has a problem with `(bit or bit32)` is that the lua interpreter there is out of date by 14 years (`print(_VERSION)` gives 5.1). Nevertheless I think your change is good -- the `require` is neater than the current solution anyways
- sorry but I'm a bit confused about the Moonscript part -- isn't Moonscript a language that compiles to lua? How does it relate to the output of wax? The hilbert example seems to compile just fine on the newest Lua and Luajit, If something isn't working with Moonscript, shouldn't it be the Moonscript author's job to fix it? Currently, this new `and/or` implementation (whatever it has to do with Moonscript), produces incorrect behavior in standard Lua, so I don't think that's very acceptable :) 

Anyways I'm happy to merge the `require` fix, and if you come up with an alternative ternary operator implementation with correct behavior, then that too.

Thanks again!

**Comment by Rabios** [comment]
Cause i did wax transpiler for MoonScript, So yep i did transpiled hilbert to MoonScript with transpiler i made for it to test it...
And from MoonScript generated code i used MoonScript to transpile generated MoonScript code to Lua...

**Comment by Rabios** [comment]
But anyway, About ternary operators, It's up to you...

**Comment by LingDong-** [comment]
Merged, and manually reverted the ternary operator. Thanks for the PR and sorry for the delay!

**Pull request merged**
